#!/bin/bash
### BEGIN INIT INFO
# Provides: omxplayer
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Display cameras for monitorings.
# Description:
### END INIT INFO

myCamera="screen -dmS myCamera sh -c 'omxplayer --live  """rtsp://192.168.1.101:5554/camera""" ' ";
camera_feeds=(camObora)

# Start displaying camera streams
case "$1" in
start)
for i in "${camera_feeds[@]}"
do
eval eval '$'$i
done
sleep 5
for i in "${camera_feeds[@]}"
do
if !(screen -list | grep -q $i)
then
	eval eval '$'$i
	sleep 5
	if !(screen -list | grep -q $i)
	then
		echo "Nie mozna uruchomic kamery $i!"
		exit 1
	else
		echo "Kamera $i jest uruchamiania..."
	fi
fi
done
;;

test)
for i in "${camera_feeds[@]}"
do
if !(screen -list | grep -q $i)
then
	echo "Kamera $i nie jest uruchomiona!"
	exit 1
else
	echo "Wszystko OK!"
fi
done
;;

stop)
sudo killall omxplayer.bin
echo "Wyłączono kamery."
;;

repair)
for i in "${camera_feeds[@]}"
do
if !(screen -list | grep -q $i)
then
	eval eval '$'$i
	sleep 5
	if !(screen -list | grep -q $i)
	then
		echo "Nie mozna uruchomic $i kamery!"
		exit 1
	else
		echo "Kamera $i jest uruchamiana..."
	fi
fi
done
;;

*)
echo "Niepoprawne polecenie. Wybierz (start | stop | repair | test)"
exit 1

;;
esac
