#!/bin/bash
### BEGIN INIT INFO
# Provides: omxplayer
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Displays camera feeds for monitoring
# Description:
### END INIT INFO

# deklaracje poszczególnych kamer
top_left="/etc/init.d/plik.bash";
# zmienne zawierające kamery 
camera_feeds=(top_left)

# Przypadek 1, uruchomienie kamer/y 
case "$1" in
start)
for i in "${camera_feeds[@]}"
do
eval eval '$'$i
done
echo "Camera Display Started"
;;

# przypadek 2, zatrzymanie kamer
stop)
sudo killall omxplayer.bin
echo "Camera Display Ended"
;;

# przypadek 3, naprawienie streamu
repair)
for i in "${camera_feeds[@]}"
do
if !(screen -list | grep -q $i)
then
eval eval '$'$i
echo "$i is now running"
fi
done
;;

# gdy nie podano dobrej komendy
*)
echo "Usage: /etc/init.d/displaycameras {start|stop|repair}"
exit 1

;;
esac 
